#!/bin/bash

#ALS and LED control program

#(C) 2017, Bo Gao

echo out > /sys/class/gpio/gpio60/direction
echo 0 > /sys/class/gpio/gpio60/value
i2cset -y 2 0x29 0x80 0x03 b
i2cset -y 2 0x29 0x81 0x12 b
